version: "3.1"
services:
  db:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: gidibooks
      POSTGRES_PASSWORD: gidibooks
      POSTGRES_DB: gidibooks
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: