version: '3'

services: 
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    image: gidibooks:prod
    expose:
      - "8000"
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py collectstatic --no-input &&
                    gunicorn gidibooks.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    env_file:
      - ./.env
    restart: "on-failure"
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: "on-failure"

  nginx:
    build: ./nginx
    image: nginx:stable
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - "80:80"
      - "10443:443"
    depends_on:
      - web
    restart: "on-failure"

volumes:
  pgdata:
  static_volume:
  media_volume: